### ISSUE TITLE
UNREACHABLE Unhandled node type: hdk::ir::Join

### ISSUE THREAD

**Issue by AndreyPavlenko** [intel-ai/hdk#253]
The following modin code:
```python
import modin.pandas as pd
df = pd.DataFrame({"a": [1]})
df = pd.merge(pd.merge(df, df.reset_index()), pd.merge(df, df.reset_index()))
print (df)
```
fails with error:
```
RelAlgExecutor.cpp:1403 UNREACHABLE Unhandled node type: hdk::ir::Join#6([#4, #5], condition=(= (ColumnRef #4:0)(ColumnRef #5:1)) , join_type=INNER
```

Execution tree:
<details>

```
JoinNode:
  Fields:
    a: frame$3.a[int64]
    index: frame$3.index[int64]
  How: inner
  Condition: (AND [(= [frame$3.a[int64], frame$5.a[int64]] [bool]), (= [frame$3.index[int64], frame$5.index[int64]] [bool])] [bool])
  input[0]:
    JoinNode:
      Fields:
        a: frame$1.a[int64]
        index: frame$2.index[int64]
      How: inner
      Condition: (= [frame$1.a[int64], frame$2.a[int64]] [bool])
      input[0]: frame$1
      input[1]: frame$2
  input[1]:
    JoinNode:
      Fields:
        a: frame$1.a[int64]
        index: frame$4.index[int64]
      How: inner
      Condition: (= [frame$1.a[int64], frame$4.a[int64]] [bool])
      input[0]: frame$1
      input[1]: frame$4
```

</details>
